import React, { useState } from 'react';
import { Clock, Thermometer, Droplets } from 'lucide-react';
import {
  Badge,
  Button,
  Card,
  PageHeader,
} from '../components/common';

interface AlertItem {
  id: string;
  type: 'TEMP_DEVIATION' | 'EXPIRY_WARNING' | 'HUMIDITY_ELEVATION';
  severity: 'WARNING' | 'CRITICAL';
  title: string;
  message: string;
  time: string;
  source: string;
  icon: React.ComponentType<{ className?: string }>;
  resolved: boolean;
}

export const AlertsPage: React.FC = () => {
  const [filter, setFilter] = useState<'ALL' | 'UNRESOLVED' | 'RESOLVED'>('ALL');
  const [alerts, setAlerts] = useState<AlertItem[]>([
    {
      id: 'ALT-101',
      type: 'TEMP_DEVIATION',
      severity: 'WARNING',
      title: 'Human Insulin Regular: Temperature Spike Detected',
      message: 'Cold chain monitor logged ambient temperature of 9.5°C, exceeding monograph maximum threshold of 8.0°C.',
      time: '15 minutes ago',
      source: 'Deterministic Temperature Boundary Rule',
      icon: Thermometer,
      resolved: false,
    },
    {
      id: 'ALT-102',
      type: 'EXPIRY_WARNING',
      severity: 'CRITICAL',
      title: 'Aspirin Gastro-Resistant: Expiry Boundary Exceeded',
      message: 'OCR extracted expiration was 2025-12. Package is past manufacturer shelf-life window.',
      time: '1 hour ago',
      source: 'OCR YYYY-MM Extraction + Deterministic Date Rule',
      icon: Clock,
      resolved: false,
    },
    {
      id: 'ALT-103',
      type: 'HUMIDITY_ELEVATION',
      severity: 'WARNING',
      title: 'Packaging Shelf Area B: Relative Humidity Alert',
      message: 'Storage environment relative humidity reached 62% RH (configured threshold: 60% max).',
      time: '3 hours ago',
      source: 'Environmental Telemetry Check',
      icon: Droplets,
      resolved: true,
    },
  ]);

  const toggleResolved = (id: string) => {
    setAlerts((prev) =>
      prev.map((a) => (a.id === id ? { ...a, resolved: !a.resolved } : a))
    );
  };

  const filteredAlerts = alerts.filter((a) => {
    if (filter === 'UNRESOLVED') return !a.resolved;
    if (filter === 'RESOLVED') return a.resolved;
    return true;
  });

  const unresolvedCount = alerts.filter((a) => !a.resolved).length;

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <PageHeader
        badge={
          <Badge variant="warning" size="sm" dot>
            Deterministic Safety Rules
          </Badge>
        }
        title="Active Storage & Expiry Discrepancy Alerts"
        description="Automated storage discrepancy alerts generated by deterministic temperature and expiration rules. Machine-learning probabilistic risk estimation will integrate into this alert stream in Phase 5."
        actions={
          <div className="rounded-xl border border-slate-800 bg-slate-900/90 px-4 py-2 text-xs text-slate-300">
            Unresolved Active:{' '}
            <span className="font-semibold text-amber-400 font-mono">{unresolvedCount} Alerts</span>
          </div>
        }
      />

      {/* Filter Toolbar */}
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-1.5 bg-slate-900/80 p-1 rounded-xl border border-slate-800 text-xs">
          <button
            type="button"
            onClick={() => setFilter('ALL')}
            className={`px-3 py-1.5 rounded-lg font-medium transition cursor-pointer ${
              filter === 'ALL'
                ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/30'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            All Alerts ({alerts.length})
          </button>
          <button
            type="button"
            onClick={() => setFilter('UNRESOLVED')}
            className={`px-3 py-1.5 rounded-lg font-medium transition cursor-pointer ${
              filter === 'UNRESOLVED'
                ? 'bg-amber-500/20 text-amber-300 border border-amber-500/30'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Unresolved ({unresolvedCount})
          </button>
          <button
            type="button"
            onClick={() => setFilter('RESOLVED')}
            className={`px-3 py-1.5 rounded-lg font-medium transition cursor-pointer ${
              filter === 'RESOLVED'
                ? 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/30'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Resolved ({alerts.length - unresolvedCount})
          </button>
        </div>

        <span className="hidden sm:inline text-xs text-slate-400">
          Click Mark Resolved to acknowledge alerts
        </span>
      </div>

      {/* Alert Cards List */}
      <div className="space-y-3">
        {filteredAlerts.map((alert) => {
          const Icon = alert.icon;
          return (
            <Card
              key={alert.id}
              variant={alert.resolved ? 'subtle' : alert.severity === 'CRITICAL' ? 'danger' : 'warning'}
              className={`p-5 transition ${alert.resolved ? 'opacity-70' : ''}`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-start gap-3.5">
                  <div
                    className={`rounded-xl p-2.5 border shrink-0 ${
                      alert.resolved
                        ? 'bg-slate-800 text-slate-400 border-slate-700'
                        : alert.severity === 'CRITICAL'
                        ? 'bg-rose-500/10 text-rose-400 border-rose-500/30'
                        : 'bg-amber-500/10 text-amber-400 border-amber-500/30'
                    }`}
                  >
                    <Icon className="h-5 w-5" />
                  </div>

                  <div className="space-y-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <h3 className="text-sm font-semibold text-white tracking-tight">
                        {alert.title}
                      </h3>
                      <Badge
                        variant={
                          alert.resolved
                            ? 'neutral'
                            : alert.severity === 'CRITICAL'
                            ? 'danger'
                            : 'warning'
                        }
                        size="sm"
                      >
                        {alert.resolved ? 'RESOLVED' : alert.severity}
                      </Badge>
                      <span className="text-[11px] font-mono text-slate-400">
                        {alert.time}
                      </span>
                    </div>

                    <p className="text-xs text-slate-300 leading-relaxed max-w-3xl">
                      {alert.message}
                    </p>

                    <div className="pt-2 flex flex-wrap items-center gap-3 text-[11px] text-slate-400 font-mono">
                      <span>Authority: <strong className="text-slate-300 font-sans">{alert.source}</strong></span>
                      <span>•</span>
                      <span className="text-cyan-400">{alert.id}</span>
                    </div>
                  </div>
                </div>

                <div className="shrink-0 self-start sm:self-center">
                  <Button
                    variant={alert.resolved ? 'outline' : 'secondary'}
                    size="sm"
                    onClick={() => toggleResolved(alert.id)}
                  >
                    {alert.resolved ? 'Reopen Alert' : 'Mark Resolved'}
                  </Button>
                </div>
              </div>
            </Card>
          );
        })}
      </div>
    </div>
  );
};
